# frozen_string_literal: true

# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Generated by scripts/extract_order.mjs from prettier-plugin-tailwindcss
# Generation time: 2025-08-10T13:38:19.947Z

module ERBLint
  module Tailwindcss
    module Support
      # Order table containing Tailwind CSS class ordering rules
      # Generated from prettier-plugin-tailwindcss to ensure compatibility
      class OrderTable
        # Class order patterns with weights (lower number = earlier in sort order)
        TAILWIND_CLASS_ORDER = {
          /^(block|inline|flex|grid|table|hidden|contents)/ => 0, # layout,
          /^(static|fixed|absolute|relative|sticky)/ => 100, # position,
          /^(inset|top|right|bottom|left)-/ => 110, # insets,
          /^(invisible|visible)/ => 200, # visibility,
          /^(flex|grid|place|justify|items|content|self|order)/ => 300, # flexbox,
          /^[pm][trblxy]?-/ => 400, # spacing,
          /^(w|h|min-w|min-h|max-w|max-h)-/ => 500, # sizing,
          /^(font|text|leading|tracking|decoration)/ => 600, # typography,
          /^bg-/ => 700, # backgrounds,
          /^(border|rounded)/ => 800, # borders,
          /^(shadow|opacity|mix|filter)/ => 900 # effects
        }.freeze

        # Variant order rules (e.g., hover:, sm:, dark:)
        VARIANT_ORDER = {
          "hover" => 1,
          "focus" => 1,
          "active" => 2,
          "disabled" => 3,
          "sm" => 4,
          "md" => 5,
          "lg" => 6,
          "xl" => 7,
          "2xl" => 8,
          "dark" => 9
        }.freeze

        # Individual class weights for exact matching
        CLASS_WEIGHTS = {
          "block" => 0,
          "inline-block" => 1,
          "inline" => 2,
          "flex" => 3,
          "inline-flex" => 4,
          "table" => 5,
          "inline-table" => 6,
          "table-caption" => 7,
          "table-cell" => 8,
          "table-column" => 9,
          "table-column-group" => 10,
          "table-footer-group" => 11,
          "table-header-group" => 12,
          "table-row-group" => 13,
          "table-row" => 14,
          "flow-root" => 15,
          "grid" => 16,
          "inline-grid" => 17,
          "contents" => 18,
          "list-item" => 19,
          "hidden" => 20,
          "flex-row" => 21,
          "flex-row-reverse" => 22,
          "flex-col" => 23,
          "flex-col-reverse" => 24,
          "flex-wrap" => 25,
          "flex-wrap-reverse" => 26,
          "flex-nowrap" => 27,
          "flex-1" => 28,
          "flex-auto" => 29,
          "flex-initial" => 30,
          "flex-none" => 31,
          "grow" => 32,
          "grow-0" => 33,
          "shrink" => 34,
          "shrink-0" => 35,
          "justify-start" => 36,
          "justify-end" => 37,
          "justify-center" => 38,
          "justify-between" => 39,
          "justify-around" => 40,
          "justify-evenly" => 41,
          "items-start" => 42,
          "items-end" => 43,
          "items-center" => 44,
          "items-baseline" => 45,
          "items-stretch" => 46,
          "p-0" => 47,
          "p-1" => 48,
          "p-2" => 49,
          "p-3" => 50,
          "p-4" => 51,
          "p-5" => 52,
          "p-6" => 53,
          "p-8" => 54,
          "p-10" => 55,
          "p-12" => 56,
          "p-16" => 57,
          "p-20" => 58,
          "p-24" => 59,
          "px-0" => 60,
          "px-1" => 61,
          "px-2" => 62,
          "px-4" => 63,
          "px-6" => 64,
          "px-8" => 65,
          "py-0" => 66,
          "py-1" => 67,
          "py-2" => 68,
          "py-4" => 69,
          "py-6" => 70,
          "py-8" => 71,
          "pt-0" => 72,
          "pt-1" => 73,
          "pt-2" => 74,
          "pt-4" => 75,
          "pb-0" => 76,
          "pb-1" => 77,
          "pb-2" => 78,
          "pb-4" => 79,
          "pl-0" => 80,
          "pl-1" => 81,
          "pl-2" => 82,
          "pl-4" => 83,
          "pr-0" => 84,
          "pr-1" => 85,
          "pr-2" => 86,
          "pr-4" => 87,
          "m-0" => 88,
          "m-1" => 89,
          "m-2" => 90,
          "m-3" => 91,
          "m-4" => 92,
          "m-5" => 93,
          "m-6" => 94,
          "m-8" => 95,
          "m-auto" => 96,
          "mx-0" => 97,
          "mx-1" => 98,
          "mx-2" => 99
          # ... and 278 more classes
        }.freeze

        class << self
          # Gets the sort weight for a given class
          # @param class_name [String] The class name to analyze
          # @return [Integer] Sort weight (lower numbers come first)
          def get_class_weight(class_name)
            # First try exact match
            return CLASS_WEIGHTS[class_name] if CLASS_WEIGHTS[class_name]

            # Then try pattern matching
            TAILWIND_CLASS_ORDER.each do |pattern, weight|
              return weight if class_name.match?(pattern)
            end

            # Default weight for unknown classes (sort alphabetically at end)
            10_000 + (class_name.hash.abs % 1000)
          end

          # Gets the sort weight for variant prefixes
          # @param variant [String] The variant name (without colon)
          # @return [Integer] Sort weight for the variant
          def get_variant_weight(variant)
            VARIANT_ORDER.fetch(variant, 10_000)
          end

          # Load order data from JSON (for future extensibility)
          def load_order_data(order_data)
            # This method allows for dynamic loading of order data
            # Implementation can be extended for custom configurations
          end
        end
      end
    end
  end
end
